# The URL the site will be built for
base_url = "https://peterlyons.com"
generate_feeds = true
feed_filenames = ["rss.xml", "atom.xml"]
compile_sass = true
build_search_index = false
title = "Pete's Points"

[markdown]
highlight_code = false
smart_punctuation = false

[extra]
# Put all your custom variables here
blog_title = "Pete's Points"

[slugify]
paths = "off"
