# The URL the site will be built for
base_url = "https://peterlyons.com"
generate_rss = true
compile_sass = true
highlight_code = false
build_search_index = false
title = "Pete's Points"

[extra]
# Put all your custom variables here
