# The URL the site will be built for
base_url = "https://peterlyons.com"
generate_feed = true
feed_filename = "rss.xml"
compile_sass = true
highlight_code = false
build_search_index = false
title = "Pete's Points"

[extra]
# Put all your custom variables here
blog_title = "Pete's Points"

[slugify]
paths = "off"
