#!/usr/bin/env bash

# Please Use Google Shell Style: https://google.github.io/styleguide/shell.xml

# ---- Start unofficial bash strict mode boilerplate
# http://redsymbol.net/articles/unofficial-bash-strict-mode/
set -o errexit  # always exit on error
set -o errtrace # trap errors in functions as well
set -o pipefail # don't ignore exit codes when piping output
set -o posix    # more strict failures in subshells
# set -x          # enable debugging

IFS="$(printf "\n\t")"
# ---- End unofficial bash strict mode boilerplate

cd "$(dirname "${BASH_SOURCE[0]}")/.."
title="$@"
# read -r -p "Title: " title
# We expect the slug CLI command to be the npm slug package
slug=$(npx slug "${title}")

publish_date=$(date -u +%Y-%m-%dT%H:%M:%SZ)
# 2018-01-03T17:32:11Z
year=$(echo "${publish_date}" | cut -d - -f 1)
month=$(echo "${publish_date}" | cut -d - -f 2)
dest_dir="content/problog/${year}/${month}/${slug}"
mkdir -p "${dest_dir}"
dest_path="${dest_dir}/index.md"
cat <<EOF >"${dest_path}"
+++
title = "${title}"
date = ${publish_date}
transparent = true
+++
EOF
./mise-tasks/transparent
"${EDITOR}" "${dest_path}"
